# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efca3d71ebad293712a08af72150eb35f238d3158974faf2c0e6aee516ed005f17e4d6252cd198fcfa215e060c70de2226f851ba24528443a161ca0eb610bd28

test:
  secret_key_base: 9852050e030caa0dcba0f7fc4c61a00feab30cae76e590ef8cc73ce2f6e97a3d611ba3b5939f5c9f513e171565e82a463740e29cbacadc1e635197f8c7df33b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
